import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar/Sidebar";
import Header from "../components/Header/Header";

import styles from "./layout.module.css";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import React from "react";
import MobileNotifyProvider from "@/components/Notifications/MobileNotifyProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Charger App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-slate-100`}>
        <Sidebar />
        
        <MobileNotifyProvider>
          <div className={`min-h-[81vh] w-full md:pl-20 ${styles.main_content}`}>
            <Header />
            <ReduxProvider>
              <main className="md:mb-0 mb-10 lg:px-9 md:px-6 px-4 py-6">{children}</main>
            </ReduxProvider>
          </div>
        </MobileNotifyProvider>
      </body>
    </html>
  );
}
